#!/usr/bin/env bash
set -euo pipefail

PROFILE_PATH="/etc/apparmor.d/codex-native"
DRY_RUN=false
VERIFY=true

usage() {
  cat <<'USAGE'
Usage: scripts/install-codex-apparmor-profile.sh [options]

Install an AppArmor profile that allows the Codex native binary to create
unprivileged user namespaces without disabling AppArmor's system-wide limit.

Run this script as the user who normally runs `codex`. The script uses sudo
only when writing /etc/apparmor.d/codex-native and loading the profile.

Options:
  --dry-run             Print the generated profile without installing it.
  --no-verify           Skip `codex sandbox /bin/true` after install.
  --profile-path PATH   Install to a different AppArmor profile path.
  -h, --help            Show this help.

Environment:
  CODEX_CMD             Override the codex command path.
USAGE
}

log() {
  printf '%s\n' "$*" >&2
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --no-verify)
      VERIFY=false
      shift
      ;;
    --profile-path)
      [[ $# -ge 2 ]] || die "--profile-path requires a path"
      PROFILE_PATH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

[[ "$(uname -s)" == "Linux" ]] || die "this script supports Linux only"

need_cmd node
need_cmd readlink
need_cmd sed
need_cmd sudo
need_cmd install
need_cmd apparmor_parser

if [[ "${EUID}" -eq 0 ]]; then
  die "run this as the normal codex user, not root; sudo is used only for AppArmor installation"
fi

CODEX_CMD="${CODEX_CMD:-}"
if [[ -z "$CODEX_CMD" ]]; then
  CODEX_CMD="$(command -v codex || true)"
fi
[[ -n "$CODEX_CMD" ]] || die "codex command not found in PATH"
[[ -x "$CODEX_CMD" ]] || die "codex command is not executable: $CODEX_CMD"

CODEX_JS="$(readlink -f "$CODEX_CMD")"
[[ -f "$CODEX_JS" ]] || die "resolved codex wrapper does not exist: $CODEX_JS"

CODEX_PACKAGE_ROOT="$(cd "$(dirname "$CODEX_JS")/.." && pwd -P)"
[[ -f "$CODEX_PACKAGE_ROOT/package.json" ]] || die "could not find @openai/codex package root from: $CODEX_JS"

NATIVE_BIN="$(
  node - "$CODEX_PACKAGE_ROOT" <<'NODE'
const { existsSync } = require("fs");
const path = require("path");

const root = process.argv[2];
const targets = {
  "linux:x64": {
    packageName: "@openai/codex-linux-x64",
    vendorTriple: "x86_64-unknown-linux-musl",
  },
  "linux:arm64": {
    packageName: "@openai/codex-linux-arm64",
    vendorTriple: "aarch64-unknown-linux-musl",
  },
};

const target = targets[`${process.platform}:${process.arch}`];
if (!target) {
  console.error(`unsupported platform/arch: ${process.platform}/${process.arch}`);
  process.exit(1);
}

const packageJson = require.resolve(`${target.packageName}/package.json`, {
  paths: [root],
});

const vendorRoot = path.join(path.dirname(packageJson), "vendor");
const packageBinaryPath = path.join(vendorRoot, target.vendorTriple, "bin", "codex");
const legacyBinaryPath = path.join(vendorRoot, target.vendorTriple, "codex", "codex");
const binaryPath = [packageBinaryPath, legacyBinaryPath].find(existsSync);

if (!binaryPath) {
  console.error(`native binary not found: ${packageBinaryPath} or ${legacyBinaryPath}`);
  process.exit(1);
}

console.log(binaryPath);
NODE
)"

[[ -x "$NATIVE_BIN" ]] || die "Codex native binary is not executable: $NATIVE_BIN"

if [[ "$NATIVE_BIN" =~ [[:space:]] ]]; then
  die "native binary path contains whitespace, which this AppArmor generator does not support: $NATIVE_BIN"
fi

CODEX_BIN_GLOB="$NATIVE_BIN"
if [[ "$CODEX_BIN_GLOB" == */installs/node/*/lib/node_modules/@openai/codex/* ]]; then
  CODEX_BIN_GLOB="$(printf '%s\n' "$CODEX_BIN_GLOB" | sed -E 's#/installs/node/[^/]+/#/installs/node/*/#')"
fi

TMP_PROFILE="$(mktemp)"
trap 'rm -f "$TMP_PROFILE"' EXIT

cat >"$TMP_PROFILE" <<EOF
# Generated by dotfiles/scripts/install-codex-apparmor-profile.sh
abi <abi/4.0>,
include <tunables/global>

@{codex_bin} = $CODEX_BIN_GLOB

profile codex-native @{codex_bin} flags=(unconfined) {
  userns,
  @{codex_bin} mr,

  include if exists <local/codex-native>
}
EOF

log "codex wrapper: $CODEX_CMD"
log "codex wrapper target: $CODEX_JS"
log "codex native binary: $NATIVE_BIN"
log "AppArmor profile path: $PROFILE_PATH"

if [[ "$DRY_RUN" == true ]]; then
  log ""
  cat "$TMP_PROFILE"
  exit 0
fi

sudo install -m 0644 "$TMP_PROFILE" "$PROFILE_PATH"
sudo apparmor_parser -r "$PROFILE_PATH"

log "installed and loaded: $PROFILE_PATH"

if [[ "$VERIFY" == true ]]; then
  log "verifying: codex sandbox /bin/true"
  codex sandbox /bin/true
  log "verification passed"
fi
